Repository schubergphilis/terraform-aws-mcaf-vpc-with-ipam, pull requests merged in 2025-03, with the labels that each got.

#12 docs: improve examples
  examples/vpc-endpoints-centralized/main.tf
  examples/vpc-endpoints-privatelink/main.tf
  examples/vpc-endpoints/main.tf
Labels: documentation

#13 feature: add support for S3 flow logging and make CloudWatch flow logging optional
  README.md
  data.tf
  flowlogs_cloudwatch.tf
  flowlogs_s3.tf
  main.tf
  modules/vpc-endpoints/README.md
  modules/vpc-endpoints/main.tf
  variables.tf
Labels: feature

#14 fix: Add optionals for s3 flowlogging
  README.md
  flowlogs_s3.tf
  variables.tf
Labels: bug, fix
